apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: mywebapp
resources:
- deployment.yaml
- service.yaml
commonAnnotations:
  app: my-kustom-annotations
namePrefix: kustom-
nameSuffix: -v1

